window.vi = {

    "title": "Cửu Long",

    // 九宮格遊戲名稱
    // "indexGame1": "Xổ Số Việt Nam",
    // "indexGame2": "Máy đanh bạc",
    // "indexGame3": "Bàn trò chơi",
    // "indexGame4": "Máy câu cá",
    // "indexGame5": "Xổ số thể thao",
    // "indexGame6": "Black Jack",
    // "indexGame7": "Fan Tan",
    // "indexGame8": "Sicbo Trăm Người",
    // "indexGame9": "Tôm Cua Cá"

    // 改各遊戲錢包顯示名稱
    // "VRGame_wallet": "VR彩票",
    // "818Game_wallet": "818娱乐",
    // "BLinkGame_wallet": "KC皇冠体育",
    // "RTGGame_wallet": "KC电子",
    // "BGGame_wallet": "KC彩票 KC真人",
    // "BLGame_wallet": "KC棋牌",
    // "DTGame_wallet": "DT电子",
    // "NGGGame_wallet": "GG彩票",
    // "WMGame_wallet": "WM真人",
    // "LCGame_wallet": "龙城棋牌",
    // "IconicGame_wallet": "IG电子 IG捕魚"
    // "YuanbaoGame_wallet": "越南彩票"

    "// App.vue": "nav-bar",
    "beijing_time": "Hồ Chí Minh, việt nam",
    "choose_line": "Chọn dòng",
    "member_page": "Trang cá nhân",
    "login": "nhập",
    "logout": "Đăng xuất",
    "switchLang": "Thay đổi ngôn ngữ",
    "free_register": "Đăng ký miễn phí",
    "mb_free_register": "Đăng ký",
    "forget_password": "Quên mật khẩu",
    "contact_cs": "Chămsóc",
    "help_center": "Trợ giúp",
    "currency": "Điểm",
    "place_login_first": "Vui lòng đăng nhập trước",
    "place_contact_cs": "Vui Chăm sóc khách hàng",
    "coming_soon": "Sắp ra mắt,  hãy theo dõi",
    "game_type": "Thể loại trò chơi",
    "kc_slot": "Điện tử KC",
    "wallet_no_money":"Số dư không đủ, vui lòng chuyển tiền",
    "enter_game": "vào trò chơi",
    "enter_game_check": "OK để vào game",
    "hot_game": "trò chơi hàng đầu",
    "logout_check": "Bạn có chắc chắn đăng xuất không?",
    "event_page":"最新活動",


    "// marquee.vue": "Marquee văn bản",
    "marquee_msg": "Chào mừng bạn đến thành phố giải trí Cửu Long",

    "// footerComp.vue": "Footer của mỗi trang",
    "partner": "Người hợp tác",
    "paying": "Phương thức thanh toán",
    "gateway": "Cổng",
    "unionPay": "Thanh toán Union",
    "union_qr": "Quét mã QR",
    "quick_pass": "Thanh toán đám mây",
    "wechat_qr": "Quét mã QR Wechat",
    "wechat_h5": "Wechat H5",
    "alipay_qr": "Quét mã Alipay",
    "alipay_h5": "Alipay H5",
    "paying_group": "Cổng trang / Thanh toán Union / Quét mã QR / Quét mã QR Wechat / Quét mã Alipay , Thanh toán H5 / Alipay H5",
    "copyright": "Tuyên bố bản quyền Copyright © Bản quyền giả trí dành riêng",
    "rule": "Điều khoản dịch vụ",
    "JB_rule": "JB có giấy phép hợp pháp được cấp bởi Cơ quan Quản lý Malta Châu Âu (MGA), Ủy ban Giám sát GC của Anh (Ủy ban Cờ bạc) và Ủy ban Đánh giá Chính trị Philippines (PAGCOR) \n. Nó được đăng ký tại Quần đảo Virgin thuộc Anh và chịu sự điều chỉnh của quốc tế Một công ty hợp pháp được hiệp hội công nhận. Trước khi đăng ký và giải trí, vui lòng đảm bảo bạn trên 18 tuổi! ",

    "// Register.vue": "Trang đăng ký",
    "register_title": "Đămg ký hội viên",
    "welcome_title": "Chào mừng bạn đến với giải trí trực tuyến, vui lòng điền đầy đủ thông tin của bạn",
    "account": "Tên tài khoản",
    "account_description": "Tên tài khoản bao gồm số và ký tự, độ dài ít nhất 6 ký tự và nhiều nhất 12 ký tự",
    "name": "Tên thật",
    "name_description": "Vui lòng điền tên thật của bạn, thẻ ngân hàng trong tương lai sẽ được sử dụng làm điểm chuẩn",
    "password": "Mật khẩu",
    "password_description": "Mật khẩu bao gồm các ký tự chữ và số",
    "chk_password": "Xác nhận mật khẩu",
    "chk_password_description": "Vui lòng xác nhận thêm mật khẩu",
    "recommended": "Người giới thiệu",
    "recommended_account": "Tên tài khoản người giới thiệu",
    "save_slogan": "Mật khẩu an toàn, bảo vệ tài sản của bạn",
    "captcha": "Mã xác nhận",
    "register": "Đăng ký nhanh",
    "had_account": "Đã có tài khoản",
    "login_now": "Đăng nhập ngay",
    "accept_kingco": "Tôi đồng ý với điều khoản của trang giải trý trực tuyến",
    "captcha_err": "Mã xác nhận không chính xác",
    "account_head_not_num": "Ký tự đầu không chấp nhận chữ số",
    "account_not_empty": "Tài khoản không được để trống",
    "account_long_six": "Tài khoản trên 6 chữ số",
    "account_include": "Tài khoản bao gồm chữ số",
    "name_not_empty": "Tên thật không được để trống",
    "password_not_empty": "Mật khẩu không được để trống",
    "password_include_eng_num": "Mật khẩu bao gồm chữ tiếng anh và chữ số",
    "chk_password_not_empty": "Xác nhận mật khẩu không được để trống",
    "chk_password_different": "Xác nhận mật khẩu và mật khẩu không khớp",
    "phone_verify_code":"手機認證碼",
    "phone_verify_code_input":"請輸入手機認證碼",
    "cant_click_under60":"60秒内不能重複點擊",
    "line_input":"請輸入line",
    "must_input":"必填",
    "phone_input":"請輸入手機",

    "// Login.vue": "Trang đăng nhập",
    "welcome_login_first": "Chào mừng, xin vui lòng đăng nhập đầu tiên",
    "username": "Tên đăng nhập",
    "login_title": "Đăng nhập",
    "account_input": "Nhập tài khoản",
    "password_input": "Vui lòng nhập mật khẩu",
    "auto_login": "Tự động đăng nhập",
    "register_now": "Đăng ký ngay",
    "account_password_err": "Lỗi tài khoản hoặc mật khẩu",
    "forget_pw_to_cs":"忘記密碼請聯繫客服",

    "// MemberCenter.vue": "Trang cá nhân",
    "welcome": "Chào mừng bạn",
    "member_level": "Cấp thành viên",
    "cell_phone": "Điện thoại",
    "mem_name": "Tên thật",
    "bank_card": "Thẻ ngân hàng",
    "mail": "Email",
    "account_balance": "Số dư",
    "point": "Điểm",
    "currency_value": "VND(K)",
    "dollar": "Đồng",
    "charge": "Gửi tiền",
    "withdrawal": "Rút tiền",
    "web_help": "Trang trợ giúp",
    "how_to_register": "Làm như thế nào để đăng ký tài khoản",
    "how_to_charge": "Làm như thế nào để nạp tiền",
    "how_to_withdrawal": "Làm như thế nào để rút tiền ",
    "account_overview": "Tổng quan",
    "agent_table": "Đại lý",
    "bet_record": "Lịch sự cược",
    "my_msg": "Tin nhắn",
    "account_detail": "Chi tiết tài khoản",
    "profile": "Trang cá nhân",
    "login_password": "Mật khẩu",
    "fund_password": "Mật khẩu thanh toán",
    "about": "Về chúng tôi",

    "// memberAccount.vue": "Trang tài sản của tôi",
    "my_property": "Tài sản",
    "one_transform_out": "Biến đổi",
    "transform_in_success": "Chuyển vào thành công",
    "transform_out_success": "Chuyển ra thành công",
    "my_profile": "Thông tin của tôi",
    "nickname": "Biệt danh",
    "QQ": "QQ",
    "wechat": "Wechat",
    "zalo": "zalo",
    "ZBLIVE": "Trực tuyến",
    "TGP": "TGP",
    "TC_lottery": "Xổ số TC",
    "SB_sport": "Thể thao",
    "SS_sport": "Thể thao SS",
    "grand_slam": "Grand Slam",
    "KY_poker": "Cờ vua KY",
    "818_crown": "Vương miệng/818",

    "// memberAccountCard": "Thẻ chuyển ra vào hồ sơ tài khoản",
    "transform_in": "Chuyển vào",
    "transform_out": "Chuyển ra",
    "flash_in": "Nhập",
    "transform_in_confirm": "Xác nhận",
    "transform_out_confirm": "Xác nhận",

    "// betRecord.vue": "Trang lich sự cược",
    "game_platform": "Nền tảng trò chơi",
    "game_big_type": "Các loại trò chơi",
    "game_platform_all": "Toàn bộ",
    "game_big_type_all": "Toàn bộ",
    "SX": "Video",
    "DZ": "Điện tử",
    "TY": "Thể thao",
    "CP": "Xổ số",
    "QP": "Cờ vua",
    "BY": "Bắn cá",
    "start_date": "Ngày bắt đầu",
    "end_date": "Ngày kết thúc",
    "to": "Từ",
    "search": "Tìm kiếm",
    "win_only": "Chỉ xem trúng thưởng",
    "platform": "Nền tảng",
    "order_id": "ID cược",
    "game": "Nội dung trò chơi",
    "game_name": "Trò chơi",
    "win_status": "Trúng thường",
    "bet_time": "Thời gian cược",
    "bet_vn_time": "VN Thời gian",
    "bet_money": "Tiền cược",
    "result": "thua",
    "state": "Trạng thái",
    "prev_page": "Trang trước",
    "next_page": "Trang sau",
    "bet_money_all": "Tổng tiền cược",
    "bet_total": "Tổng cược",

    "// memberMessage.vue": "Trang thông tin cúa tôi",
    "sys_announcement": "Thông",
    "date": "Ngày",
    "msg_time": "Thông tin thời gian",
    "all_time": "Toàn bộ thời gian",
    "today": "Hôm nay",
    "yesterday": "Ngày mai",
    "one_week": "Một tuần",
    "one_month": "Một tháng",
    "only_non_read": "Chỉ xem không đọc",
    "msg": "Tin nhắn",
    "announcement": "Thông báo",
    "one_click_read": "đã đọc",
    "filter_status": "Trạng thái",
    "select_time": "Chọn giờ",
    "mm_not_read": "Chưa đọc",
    "mm_read": "Đã đọc",
    "mm_all": "Toàn bộ",

    "// memberDeposit.vue": "Trang gửi tiền",
    "pay_way": "Trang thanh toán",
    "third_payment_bank": "Ngân hàng thanh toán thứ ba",
    "ali_pay": "Thanh toán Alipay",
    "icbc_bank": "Ngân hàng ICBC",
    "agricultural_bank": "Ngân hàng Agricultura",
    "construction_bank": "Ngân hàng Construction",
    "cmbc_bank": "Ngân hàng CMBC",
    "china_post": "Bưu điện Trung Quốc",
    "everbright_bank": "Ngân hàng Everbright",
    "beijing_bank": "Ngân hàng Beijing",
    "shanghai_bank": "Ngân hàng Shanghai",
    "deposit_way_help": "Mô tả tranh thanh toán",
    "scan_code": "Quét mã",
    "union_pay": "Thanh toán Union",
    "pay": "Thanh toán",
    "web_bank": "Trang web ngân hàng",
    "charge_money": "Tiền gửi",
    "input_money": "Nhập số tiền",
    "choose_saving_bank": "Không có kênh thanh toán nào được chọn",
    "choose_third_bank": "Không có ngân hàng thứ ba nào được chọn",
    "not_input_money": "Chưa nhập số tiền",
    "ig_description": "Iconic Game：Chuyển 1 = 1k",
    "LCGame_description": "Bàn trò chơi：Chuyển 1 = 1k",
    "cv_charge": "Cửa hàng tiện dụng",
    "virtual_ATM": "Chuyển tiền",
    "cv_charge_help": "Cửa hàng tiện dụng: Tối thiểu là $100(TWD), tối đa là $20,000(TWD).",
    "virtual_ATM_help": "Chuyển tiền: Tối thiểu là $100(TWD), tối đa là $20,000(TWD).",
    "cv_charge_description": "Cửa hàng tiện dụng: $100(TWD) ~ $20,000(TWD)",
    "virtual_ATM_description": "Chuyển tiền: $100(TWD) ~ $20,000(TWD)",

    "// memberDetail.vue": "Trang chi tiết tài khoản",
    "account_record": "Lịch sử",
    "charge_record": "Lịch sử",
    "withdraw_record": "Lịch sử",
    "account_type": "Loại tài khoản",
    "reason": "Nguyên nhân",
    "account_charge": "Phí tài khoản",
    "balance": "Số dư",
    "detail": "Chi tiết",
    "amount": "Số tiền",
    "account_record_time": "Thời gian",
    "account_record_detail": "Chi tiết",
    "empty": "Ô trống",
    "load_more": "Tải thêm",
    "no_result": "Không tìm thấy thông tin đủ điều kiện",

    "// memberEdit.vue": "Trang thông tin cá nhân",
    "place_input_nickname": "Vui lòng nhập biệt danh",
    "same_to_account_name": "Tên người chơi và tên tài khoản thẻ ngân hàng bắt buộc giống nhau",
    "name_warning": "Tên thật và tên tài khoản thẻ ngân hàng bắt buộc giống nhau , nếu không thanh toán sẽ không được thực hiện",
    "place_input_cellphone": "Vui lòng nhập số điện thoại",
    "place_input_mail": "Vui lòng nhập nhập địa chỉ email",
    "place_input_qq": "Vui lòng nhập tài khoản QQ",
    "place_input_wechat": "Vui lòng nhập tài khoản Wechat",
    "place_input_zalo": "Vui lòng nhập tài khoản Zalo",
    "place_input_line": "Vui lòng nhập tài khoản Line",
    "place_input_skype": "Vui lòng nhập tài khoản Skype",
    "cancel": "Hủy bỏ",
    "save": "Lưu",
    "phone_mail_not_empty": "Số điện thoại, địa chỉ email không được bỏ trống",
    "phone_illegal": "Định dạng điện thoại không đúng",
    "email_illegal": "Định dạng email không đúng",
    "edit_success": "修改成功",
    "profile_notice_1":"已提供過的個人資料將無法自行異動。",
    "profile_notice_2":"若需異動個人資料，請聯繫客服",

    "// memberChangeFundPassword.vue": "Trang thay đổi mật khẩu thanh toán",
    "change_login_password": "Thay đổi mật khẩu",
    "change_fund_password": "Thay đổi mật khẩu thanh toán",
    "old_password": "Mật khẩu cũ",
    "place_input_old_password": "Vui nhập nhập mật khẩu cũ",
    "new_password": "Mật khẩu mới",
    "place_input_new_password": "Vui lòng nhập mật khẩu mới",
    "new_password_help": "Mật khẩu bao gồm ký tự chữ và số",
    "chk_new_password": "Xác nhận mật khẩu",
    "submit": "Xác nhận",
    "friendly_reminders": "Xin nhắc nhở",
    "save_is_more_important": "Trúng thưởng rất quan trọng , tài khoản an toàn quan trọng hơn. Chúng tôi khuyên bạn nên ràng buộc tất cả các thông tin bảo mật để bảo vệ tài khoản và tiền của bạn.",
    "old_password_not_empty": "Mật khẩu cũ không được để trống",
    "new_password_not_empty": "Mật khẩu mới không được để trống",
    "cant_edit_password":"請聯絡客服進行修改資金密碼",
    "login_password_notice_1":"login_password_notice_1",

    "// memberBankCard.vue": "Trang thẻ ngân hàng",
    "welcome_bank_card_first": "Thêm thẻ ngân hàng",
    "creator_bank_card": "Thêm thẻ ngân hàng",
    "card_id": "Số thẻ",
    "account_name": "Tên tài khoản",
    "edit": "Chỉnh sửa",
    "delete": "Xóa",
    "set_default": "Cài làm mặc định",
    "bind_new_bank_card": "Mặc định thẻ ngân hàng mới",
    "edit_bank_card": "Chỉnh sửa",
    "opening_bank": "Mở thẻ",
    "choose_opening_bank": "Chọn tài khoản ngân hàng",
    "opening_bank_province": "tỉnh",
    "choose_opening_bank_province": "Chọn tỉnh",
    "opening_bank_city": "thành phố",
    "choose_opening_bank_city": "Chọn thành phố",
    "branch_name": "Chi nánh",
    "opening_name": "Tên tài khoản",
    "please_input_opening_name": "Vui lòng nhập tên tài khoản",
    "bank_card_id": "Số thẻ ngân hàng",
    "please_input_bank_card_id": "Vui lòng nhập số thẻ ngân hàng",
    "fund_password_default_login_password": "Mật khẩu thanh toán chưa được sửa đổi là mặc định mật khẩu đăng nhập",
    "save_bank_card": "Lưu thẻ ngân hàng",
    "delete_bank_card": "Xóa thẻ ngân hàng",
    "no_empty": "Thông tin không được bỏ trống",
    "account_name_no_number": "Tên không được bỏ trống",
    "please_set_fundPassword": "Vui lòng nhập mật khẩu thanh toán",
    "payment_account_illegal": "Số thẻ ngân hàng là bất hợp pháp",
    "bankcard_notice_1":"請綁定正確的銀行卡，否則會影響出款權益",
    "bankcard_notice_2":"請先設定支付密碼，若未設置將無法添加銀行卡",

    "// memberWithdraw.vue": "Trang rút tiền",
    "withdraw_amount": "Số tiền rút",
    "please_input_withdraw_amount": "Vui lòng nhập số tiền rút",
    "fundPassword": "Mật khẩu",
    "please_input_fundPassword": "Vui lòng nhập mật khẩu thanh toán",
    "withdraw_amount_must_10": "Số tiền rút tối đa là 10 chữ số",
    "please_choose_bank": "Vui lòng chọn thẻ ngân hàng",
    "orderComment": "Để lại tin nhắn",
    "please_input_orderComment": "Vui lòng nhập tin nhắn",
    "withdraw_notice_1":"單筆托售對低額度1000點，最高99999999點",
    "withdraw_notice_2":"請注意：如有利用本平台進行任何洗錢或是詐騙行為，本公司保留權力凍結會員帳戶或是終止會員所有服務",


    "// parseTool.js": "Thay đổi công cụ",
    "processing": "Đang xử lý",
    "done": "Đã hoàn tất",
    "return": "Trả về",
    "refuse": "Từ chối",
    "wait_withdraw": "Đợi xuất khoản",
    "not_read": "Chưa đọc",
    "read": "Đã đọc",
    "unbalanced": "Chưa giải quyết",
    "win": "Thắng",
    "lose": "Thua",
    "bet_canceled": "Phiếu cược hủy bỏ",
    "bet_rebalanced": "Phiếu cược đang tiến hành",
    "draw": "Hòa",
    "cancel_bet_himself": "Hủy đặt cược ",
    "bet_fail": "Cược thất bại",

    "// tab bar for mobile": "Phiên bản điện thoại, chọn nút bấm bên dưới",
    "tab_home": "Trang đầu",
    "tab_discount": "Khuyến mãi",
    "tab_account_center": "Trung tâm",

    "// api platform name": "遊戲平台名稱",
    "VRGame": "Xổ số VR",
    "818Game": "Giải trí 818",
    "BLinkGame": "Thể thao vương miện",
    "RTGGame": "Điện tử RTG",
    "BGGame": "Bắn cá KC người thật BG",
    "BLGame": "Cờ vua KC",
    "DTGame": "Điện tử DT",
    "NGGGame": "Xổ  số GG",
    "WMGame": "WM Live",
    "LCGame": "Bàn trò chơi",
    "IconicGame": "Iconic Game",
    "ZYGame": "Cờ bơi thật",

    "// memberHelp.vue": "Trung tâm trợ giúp",
    "about_text": "Với nền tảng vững chắc và công nghệ chuyên nghiệp, chúng tôi cung cấp cho bạn nền tảng sòng bạc trực tuyến tốt nhất! Là một nhà điều hành trò chơi đánh bạc trực tuyến chuyên nghiệp quốc tế chúng tôi xin hứa cung cấp trò chơi trực tuyến và các dịch vụ khác an toàn và công bằng nhất cho mọi khách hàng.",
    "how_to_register_text": "Vui lòng chọn [ Nút mở tài khoản miễn phí ] để tiến hành đăng ký, chỉ cần điền vài thông tin đơn giản trong 30 giây bạn đã có thể đăng ký thành công!",
    "how_to_charge_text": "Trước khi bạn sẵn sàng đặt cược, bạn có thể gửi tiền vào tài khoản của mình bằng các phương thức sau: Gửi tiền trực tuyến - Thanh toán bên thứ ba - Thanh toán trực tuyến - Chuyển khoản ngân hàng trực tuyến. Lưu ý: Quản trị viên sẽ không chấp nhận bất kỳ séc ngân hàng hoặc tiền gửi ngân hàng thẻ tín dụng để gửi tiền nhanh hơn vào tài khoản của bạn. Vui lòng sử dụng phương thức gửi tiền được đề xuất ở trên.",
    "how_to_withdrawal_text": "Chúng tôi cung cấp phương thức chuyển khoản ngân hàng. Sau khi gửi yêu cầu, chúng tôi sẽ xử lý việc rút tiền cho bạn sau 5-30 phút. Khi nhận được yêu cầu rút tiền của bạn, quy trình rút tiền sẽ được thực hiện như sau: Tính từ khi nhận được yêu cầu rút tiền, thời gian xử lý yêu cầu: 5-30 phút, thời gian hoàn tất cụ thể phải dựa trên thời gian chuyển khoản ngân hàng Rút tiền không tính phí. Tuy nhiên, xin lưu ý rằng, ngân hàng mà bạn sử dụng tính phí đó không phải từ trang trực tuyến của chúng tôi . Tất cả các khoản phí gửi và rút tiền từ ngân hàng đều do người dùng tự chịu và chúng tôi sẽ không xử lý chúng. Nếu bạn có bất kỳ câu hỏi, xin vui lòng liên hệ với dịch vụ khách hàng trực tuyến kịp thời",

    "// Activity.vue": "Phiên bản điện thoại",
    "normal": "Bình thường",
    "special": "Đặc biệt",

    "// LCGame": "龍城棋牌",
    "Hall":"Sảnh",
    "Three Cards":"Hoa vàng chiên",
    "fishing":"Kiệt tác câu cá",
    "Black Jack":"21 giờ",
    "Fight the poker":"Chủ nhà",
    "Texas Hold’em poker":"Texas Hold'em",
    "Thirteen Cards:":"Mười ba vùng biển",
    "Play out":"Chạy nhanh",
    "Two-Eight Gong":"Hai tám thanh",
    "Pai Gow":"Lấy Zhuang Pai Gow",
    "2 men Mahjong":"Hai mạt chược",
    "Bull-bull":"Lấy Zhuang Niu Niu",
    "ThreeToy":"San Công",
    "Casino bull-bull":"Tomby Niu Niu",
    "Four Cards Bull":"Nhìn vào bốn thẻ",
    "Long-Hu Battle":"Rồng chiến đấu",
    "Baccarat":"Baccarat",
    "Hundreds Person of Bull":"Trăm người Niu Niu",
    "Red - black war":"Đỏ và Đen",
    "Brag":"Khoe khoang",
    "War bull":"Đánh nhau Niu Niu",
    "Five Choices Thr":"Năm lựa chọn của Zhuang Zhuang",
    "Changeable bull":"Zhuang Bạch ngẫu nhiên",
    "Hundred sic Bo":"Trăm Sic Bo",
    "3+2 Fried Golden Flower":"Hoa vàng chiên 3 + 2",
    "At ten thirty":"10:30",
    "red pocket":"Phong bì màu đỏ sấm sét",
    "Crazy Six Cattle":"Điên 6",
    "Lucky Fruit Machine":"Quả may mắn",
    "Fish-Shrimp-Crab":"Cá, tôm và cua",
    "Fan Tan":"Fan Tan",
    "Claim Black Jack":"Lấy làng 2",
    "Look Cards Three Toy":"Nhìn vào thẻ để lấy Zhuangsan",
    "Happy Bull":"Đấu bò vui vẻ",

};
